Update remote-job.yml

diff --git a/.github/workflows/remote-job.yml b/.github/workflows/remote-job.yml
--- a/.github/workflows/remote-job.yml
+++ b/.github/workflows/remote-job.yml
@@ -30,6 +30,8 @@ jobs:
           else
             echo "passing job"
           fi
+          # Force failure
+          exit 1
           
       - name: Report failure
         if: ${{ failure() }}
